trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build frontend'
  workingDirectory: frontend

- script: |
    npm install
    npm run build
  displayName: 'Build backend'
  workingDirectory: backend

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)\backend\dist'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1 
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 107j_nieuwjaarsspel
  displayName: 'Publish webapp'